services:
  postgres:
    image: postgres:16-alpine
    container_name: pfm-postgres-dev
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: pfm_db
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - '5434:5432'
    volumes:
      - postgres_data_dev:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - pfm-network-dev

volumes:
  postgres_data_dev:

networks:
  pfm-network-dev:
    driver: bridge
